// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	inefficientComparable "github.com/reeceappling/measurements/units/numericalPair/pairs/inefficientComparable"
	mock "github.com/stretchr/testify/mock"
)

// IC is an autogenerated mock type for the IC type
type IC[T interface{}] struct {
	mock.Mock
}

// EqualTo provides a mock function with given fields: _a0
func (_m *IC[T]) EqualTo(_a0 inefficientComparable.IC[T]) bool {
	ret := _m.Called(_a0)

	var r0 bool
	if rf, ok := ret.Get(0).(func(inefficientComparable.IC[T]) bool); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// InefficientlyComparableValue provides a mock function with given fields:
func (_m *IC[T]) InefficientlyComparableValue() T {
	ret := _m.Called()

	var r0 T
	if rf, ok := ret.Get(0).(func() T); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(T)
	}

	return r0
}

type mockConstructorTestingTNewIC interface {
	mock.TestingT
	Cleanup(func())
}

// NewIC creates a new instance of IC. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIC[T interface{}](t mockConstructorTestingTNewIC) *IC[T] {
	mock := &IC[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
